Rect(x=2, y=3, width=10, height=4)
12 7
True True False False
Rect(x=3, y=4, width=8, height=2)
False True
Rect(x=4, y=4, width=2, height=2)
Rect(x=4, y=4, width=2, height=2)
Rect(x=10, y=10, width=0, height=0)
Rect(x=2, y=3, width=10, height=1)
Rect(x=2, y=4, width=10, height=3)
Rect(x=2, y=3, width=10, height=2)
Rect(x=2, y=5, width=10, height=2)
Rect(x=2, y=3, width=3, height=4)
Rect(x=5, y=3, width=7, height=4)
(Rect(x=2, y=3, width=10, height=4), Rect(x=2, y=7, width=10, height=0))
31
241
30
127
135
7
