# dict.py - Dict method stubs for PyDOS
from _internal import internal_implementation

class dict:
    @internal_implementation("pydos_dict_get_")
    def __getitem__(self, key): ...

    @internal_implementation("pydos_dict_set_")
    def __setitem__(self, key, value) -> None: ...

    @internal_implementation("pydos_obj_contains_")
    def __contains__(self, key) -> bool: ...

    @internal_implementation("pydos_dict_get_", fast_argc=1)
    def get(self, key, default=None): ...

    def keys(self) -> list: ...

    def values(self) -> list: ...

    def items(self) -> list: ...

    def pop(self, key): ...

    def update(self, other) -> None: ...

    @internal_implementation("pydos_dict_clear_")
    def clear(self) -> None: ...

    def setdefault(self, key, default): ...

    def copy(self) -> dict: ...

    def popitem(self) -> tuple: ...
