# funcs.py - Builtin function stubs for PyDOS
#
# These stubs are the single source of truth for stdlibgen.
# stdlibgen parses these .py files to generate stdlib.idx.

from _internal import internal_implementation

# --- Standard builtins ---

@internal_implementation("pydos_builtin_print_")
def print(*args) -> None: ...

@internal_implementation("pydos_builtin_input_")
def input(prompt: str = "") -> str: ...

@internal_implementation("pydos_builtin_len_")
def len(obj) -> int: ...

@internal_implementation("pydos_builtin_range_")
def range(start: int, stop: int = 0, step: int = 1) -> range: ...

@internal_implementation("pydos_builtin_type_")
def type(obj) -> str: ...

@internal_implementation("pydos_builtin_isinstance_")
def isinstance(obj, classinfo) -> bool: ...

@internal_implementation("pydos_builtin_issubclass_")
def issubclass(cls, classinfo) -> bool: ...

@internal_implementation("pydos_builtin_int_conv_")
def int(x=0) -> int: ...

@internal_implementation("pydos_builtin_str_conv_")
def str(x="") -> str: ...

@internal_implementation("pydos_builtin_bool_conv_")
def bool(x=False) -> bool: ...

@internal_implementation("pydos_builtin_float_conv_")
def float(x=0) -> float: ...

@internal_implementation("pydos_builtin_list_conv_")
def list(iterable=None) -> list: ...

@internal_implementation("pydos_builtin_dict_conv_")
def dict() -> dict: ...

@internal_implementation("pydos_builtin_frozenset_conv_")
def frozenset(iterable=None) -> frozenset: ...

@internal_implementation("pydos_builtin_complex_conv_")
def complex(real=None, imag=None) -> complex: ...

@internal_implementation("pydos_builtin_bytearray_conv_")
def bytearray(source=None) -> bytearray: ...

@internal_implementation("pydos_builtin_iter_")
def iter(obj) -> object: ...

@internal_implementation("pydos_builtin_abs_")
def abs(x: int) -> int: ...

def min(a, b) -> object: ...

def max(a, b) -> object: ...

@internal_implementation("pydos_builtin_ord_")
def ord(c: str) -> int: ...

@internal_implementation("pydos_builtin_chr_")
def chr(i: int) -> str: ...

@internal_implementation("pydos_builtin_hex_")
def hex(i: int) -> str: ...

@internal_implementation("pydos_builtin_open_")
def open(path: str, mode: str = "r") -> object: ...

def enumerate(iterable) -> object: ...

def zip(a, b) -> object: ...

def map(func, iterable) -> object: ...

def filter(func, iterable) -> object: ...

def sorted(iterable) -> list: ...

def reversed(seq) -> object: ...

def sum(iterable) -> int: ...

@internal_implementation("pydos_builtin_id_")
def id(obj) -> int: ...

@internal_implementation("pydos_builtin_hasattr_")
def hasattr(obj, name: str) -> bool: ...

@internal_implementation("pydos_builtin_getattr_")
def getattr(obj, name: str) -> object: ...

@internal_implementation("pydos_builtin_setattr_")
def setattr(obj, name: str, value) -> None: ...

@internal_implementation("pydos_builtin_super_")
def super() -> object: ...

def any(iterable) -> bool: ...

def all(iterable) -> bool: ...

@internal_implementation("pydos_builtin_next_")
def next(iterator) -> object: ...

@internal_implementation("pydos_builtin_repr_")
def repr(obj) -> str: ...

@internal_implementation("pydos_builtin_hash_")
def hash(obj) -> int: ...

# --- Async builtins ---

@internal_implementation("pydos_async_run_")
def async_run(coro) -> object: ...

@internal_implementation("pydos_async_gather_")
def async_gather(tasks) -> list: ...

# --- Internal helpers (not Python-callable, used by generated code) ---

@internal_implementation("pydos_unpack_ex_")
def pydos_unpack_ex(seq, before: int, after: int) -> list: ...

@internal_implementation("pydos_excgroup_match_")
def pydos_excgroup_match(exc, type_code: int) -> list: ...

# --- Exception constructors ---

@internal_implementation("pydos_exc_new_valueerror_", exc_code=3)
def ValueError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_typeerror_", exc_code=2)
def TypeError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_runtimeerror_", exc_code=8)
def RuntimeError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_indexerror_", exc_code=5)
def IndexError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_keyerror_", exc_code=4)
def KeyError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_stopiteration_", exc_code=9)
def StopIteration() -> object: ...

@internal_implementation("pydos_exc_new_exception_", exc_code=1)
def Exception(msg="") -> object: ...

@internal_implementation("pydos_exc_new_baseexception_", exc_code=0)
def BaseException(msg="") -> object: ...

@internal_implementation("pydos_exc_new_assertionerror_", exc_code=15)
def AssertionError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_attributeerror_", exc_code=6)
def AttributeError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_nameerror_", exc_code=7)
def NameError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_zerodivisionerror_", exc_code=10)
def ZeroDivisionError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_overflowerror_", exc_code=11)
def OverflowError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_oserror_", exc_code=12)
def OSError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_notimplementederror_", exc_code=13)
def NotImplementedError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_memoryerror_", exc_code=14)
def MemoryError() -> object: ...

@internal_implementation("pydos_exc_new_exceptiongroup_", exc_code=17)
def ExceptionGroup(msg, exceptions) -> object: ...

# --- Phase 6A: new exception types ---

@internal_implementation("pydos_exc_new_lookuperror_", exc_code=18)
def LookupError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_arithmeticerror_", exc_code=19)
def ArithmeticError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_systemexit_", exc_code=20)
def SystemExit(msg="") -> object: ...

@internal_implementation("pydos_exc_new_keyboardinterrupt_", exc_code=21)
def KeyboardInterrupt(msg="") -> object: ...

@internal_implementation("pydos_exc_new_importerror_", exc_code=22)
def ImportError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_modulenotfounderror_", exc_code=23)
def ModuleNotFoundError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_syntaxerror_", exc_code=24)
def SyntaxError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_indentationerror_", exc_code=25)
def IndentationError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_unboundlocalerror_", exc_code=26)
def UnboundLocalError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_floatingpointerror_", exc_code=27)
def FloatingPointError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_filenotfounderror_", exc_code=28)
def FileNotFoundError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_permissionerror_", exc_code=29)
def PermissionError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_unicodeerror_", exc_code=30)
def UnicodeError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_unicodedecodeerror_", exc_code=31)
def UnicodeDecodeError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_unicodeencodeerror_", exc_code=32)
def UnicodeEncodeError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_buffererror_", exc_code=33)
def BufferError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_eoferror_", exc_code=34)
def EOFError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_recursionerror_", exc_code=35)
def RecursionError(msg="") -> object: ...

@internal_implementation("pydos_exc_new_stopasynciteration_", exc_code=36)
def StopAsyncIteration() -> object: ...

@internal_implementation("pydos_exc_new_timeouterror_", exc_code=37)
def TimeoutError(msg="") -> object: ...
