# list.py - List method stubs for PyDOS
from _internal import internal_implementation

class list:
    @internal_implementation("pydos_list_get_")
    def __getitem__(self, index: int): ...

    @internal_implementation("pydos_list_set_")
    def __setitem__(self, index: int, value) -> None: ...

    @internal_implementation("pydos_list_slice_")
    def __getslice__(self, start: int, stop: int, step: int): ...

    @internal_implementation("pydos_list_append_")
    def append(self, item) -> None: ...

    @internal_implementation("pydos_list_insert_m_")
    def insert(self, index: int, item) -> None: ...

    def extend(self, iterable) -> None: ...

    def remove(self, item) -> None: ...

    @internal_implementation("pydos_list_clear_")
    def clear(self) -> None: ...

    @internal_implementation("pydos_list_reverse_")
    def reverse(self) -> None: ...

    @internal_implementation("pydos_list_sort_")
    def sort(self) -> None: ...

    @internal_implementation("pydos_list_pop_m_")
    def pop(self, index: int = -1): ...

    def index(self, item) -> int: ...

    def count(self, item) -> int: ...

    def copy(self) -> list: ...
