# set.py - Set method stubs for PyDOS
from _internal import internal_implementation

class set:
    @internal_implementation("pydos_obj_contains_")
    def __contains__(self, item) -> bool: ...

    @internal_implementation("pydos_set_add_")
    def add(self, item) -> None: ...

    @internal_implementation("pydos_set_remove_")
    def remove(self, item) -> None: ...

    @internal_implementation("pydos_set_discard_")
    def discard(self, item) -> None: ...

    @internal_implementation("pydos_set_clear_")
    def clear(self) -> None: ...

    @internal_implementation("pydos_set_pop_")
    def pop(self): ...

    def union(self, other) -> set: ...

    def intersection(self, other) -> set: ...

    def difference(self, other) -> set: ...

    def symmetric_difference(self, other) -> set: ...

    def copy(self) -> set: ...

    def issubset(self, other) -> bool: ...

    def issuperset(self, other) -> bool: ...

    def isdisjoint(self, other) -> bool: ...

    def update(self, other) -> None: ...
