# str.py - String method stubs for PyDOS
from _internal import internal_implementation

class str:
    @internal_implementation("pydos_str_index_")
    def __getitem__(self, index: int): ...

    @internal_implementation("pydos_str_slice_")
    def __getslice__(self, start: int, stop: int, step: int): ...

    @internal_implementation("pydos_obj_contains_")
    def __contains__(self, sub: str) -> bool: ...

    @internal_implementation("pydos_str_upper_")
    def upper(self) -> str: ...

    @internal_implementation("pydos_str_lower_")
    def lower(self) -> str: ...

    @internal_implementation("pydos_str_strip_")
    def strip(self) -> str: ...

    @internal_implementation("pydos_str_lstrip_")
    def lstrip(self) -> str: ...

    @internal_implementation("pydos_str_rstrip_")
    def rstrip(self) -> str: ...

    @internal_implementation("pydos_str_title_")
    def title(self) -> str: ...

    @internal_implementation("pydos_str_capitalize_")
    def capitalize(self) -> str: ...

    @internal_implementation("pydos_str_swapcase_")
    def swapcase(self) -> str: ...

    @internal_implementation("pydos_str_replace_m_")
    def replace(self, old: str, new: str) -> str: ...

    @internal_implementation("pydos_str_format_m_")
    def format(self, *args) -> str: ...

    @internal_implementation("pydos_str_join_m_")
    def join(self, iterable) -> str: ...

    @internal_implementation("pydos_str_encode_")
    def encode(self) -> str: ...

    @internal_implementation("pydos_str_center_m_")
    def center(self, width: int, fillchar: str = " ") -> str: ...

    @internal_implementation("pydos_str_ljust_m_")
    def ljust(self, width: int, fillchar: str = " ") -> str: ...

    @internal_implementation("pydos_str_rjust_m_")
    def rjust(self, width: int, fillchar: str = " ") -> str: ...

    @internal_implementation("pydos_str_zfill_m_")
    def zfill(self, width: int) -> str: ...

    @internal_implementation("pydos_str_find_m_")
    def find(self, sub: str) -> int: ...

    @internal_implementation("pydos_str_rfind_m_")
    def rfind(self, sub: str) -> int: ...

    @internal_implementation("pydos_str_index_m_")
    def index(self, sub: str) -> int: ...

    @internal_implementation("pydos_str_rindex_m_")
    def rindex(self, sub: str) -> int: ...

    @internal_implementation("pydos_str_count_m_")
    def count(self, sub: str) -> int: ...

    @internal_implementation("pydos_str_split_m_")
    def split(self, sep=None) -> list: ...

    @internal_implementation("pydos_str_rsplit_m_")
    def rsplit(self, sep=None) -> list: ...

    @internal_implementation("pydos_str_splitlines_")
    def splitlines(self) -> list: ...

    @internal_implementation("pydos_str_startswith_")
    def startswith(self, prefix: str) -> bool: ...

    @internal_implementation("pydos_str_endswith_")
    def endswith(self, suffix: str) -> bool: ...

    @internal_implementation("pydos_str_isdigit_")
    def isdigit(self) -> bool: ...

    @internal_implementation("pydos_str_isalpha_")
    def isalpha(self) -> bool: ...

    @internal_implementation("pydos_str_isalnum_")
    def isalnum(self) -> bool: ...

    @internal_implementation("pydos_str_isspace_")
    def isspace(self) -> bool: ...

    @internal_implementation("pydos_str_isupper_")
    def isupper(self) -> bool: ...

    @internal_implementation("pydos_str_islower_")
    def islower(self) -> bool: ...
