/*
 * iropt.h - IR optimization passes
 *
 * Provides constant folding, dead code elimination, copy propagation,
 * strength reduction, and peephole optimizations for the three-address
 * code IR generated by ir.cpp.
 *
 * C++98 compatible, Open Watcom targeting 8086 real-mode DOS.
 * No STL - arrays, linked lists, manual memory only.
 */

#ifndef IROPT_H
#define IROPT_H

#include "ir.h"

class IROptimizer {
public:
    IROptimizer();
    ~IROptimizer();

    /* Run all optimization passes on every function in the module */
    void optimize(IRModule *mod);

    /* Individual passes (can be invoked separately for testing) */
    void constant_fold(IRFunc *func);
    void dead_code_eliminate(IRFunc *func);
    void copy_propagate(IRFunc *func);
    void strength_reduce(IRFunc *func);
    void peephole(IRFunc *func);

private:
    /* -------------------------------------------------------------- */
    /* Constant tracking for folding                                   */
    /* -------------------------------------------------------------- */
    struct ConstValue {
        int     is_const;       /* non-zero if this temp is a known constant */
        IRConst value;          /* the constant value */
    };
    enum { MAX_TRACKED_TEMPS = 1024 };
    ConstValue temp_consts[MAX_TRACKED_TEMPS];
    int        num_temp_consts;

    /* Module pointer for accessing / adding constants during folding */
    IRModule *current_mod;

    /* -------------------------------------------------------------- */
    /* Helpers                                                         */
    /* -------------------------------------------------------------- */

    /* Return non-zero if instruction has no side effects and its only
     * purpose is to compute its dest value. */
    int is_pure(IROp op);

    /* Return non-zero if 'temp' is read by any instruction after
     * 'after' (exclusive) within the same function. */
    int is_temp_used_after(IRFunc *func, IRInstr *after, int temp);

    /* Return non-zero if 'temp' is read by any instruction in func. */
    int is_temp_used(IRFunc *func, int temp);

    /* Unlink instruction from doubly-linked list and free it. */
    void remove_instr(IRFunc *func, IRInstr *instr);

    /* Replace an instruction with NOP (preserves list position). */
    void nop_out(IRInstr *instr);

    /* Return non-zero if 'temp' appears as src1, src2, or extra
     * (where applicable) of instruction 'ins'. */
    int instr_reads_temp(IRInstr *ins, int temp);

    /* Reset the temp_consts tracking array. */
    void reset_const_tracking();

    /* Record a known constant for a temp. */
    void set_const(int temp, const IRConst *val);

    /* Query whether a temp has a known constant value.
     * Returns pointer to ConstValue if known, else 0. */
    ConstValue *get_const(int temp);

    /* Return non-zero if 'val' is an integer power of 2, and
     * write the log2 to *shift_out. */
    int is_power_of_two(long val, int *shift_out);
};

#endif /* IROPT_H */
